### PR TITLE
Add post about sABRTooth

### PR DESCRIPTION
**Pull request by ernestask**

### CODE REVIEW

**Review by michalfabik — APPROVED** [review]

**Comment by xsuchy** [comment]
I would recommend uploading the video to youtube (or Vimeo or whatever) and put a link here. Those services handle playback issues for you.

**Comment by ernestask** [comment]
I don’t have a YouTube (or a Vimeo) account. Would prefer to not have one as well.

**Comment by ernestask** [comment]
So I can either try to find something hosted on Fedora/Red Hat infra or ask someone else to do it.

**Comment by michalfabik** [comment]
> I don’t have a YouTube [...] account  
  
FWIW, I think you can use your redhat.com account to log into YT.

**Comment by ernestask** [comment]
> FWIW, I think you can use your redhat.com account to log into YT.

I wonder what would happen to it if I ever left. If the video suddenly becomes inaccessible, then it’s kind of shitty.

**Comment by ernestask** [comment]
Good thinking, though. I can try to dig up some more information about it.

**Comment by xsuchy** [comment]
I uploaded it as https://youtu.be/tf0MTM3qIfg

**Pull request merged**
