### PR TITLE
Add article about the new FAF changes in Openshift

### PR DESCRIPTION
**Pull request by mkutlak**
The FAF and the database for FAF now run in two different containers.

Signed-off-by: Martin Kutlak <mkutlak@redhat.com>

### CODE REVIEW

**Comment by marusak** [comment]
Would be nice to write there which version of FAF and postgres-semver you used in case, that somebody will try this in a long time. I'll release new FAF today and also create postgres-semver project.
But I cannot decide what version should I put to the postgres-semver image. Should I start from 1.0 ? Or should I match with FAF (1.2.2)? Ideas @mkutlak @xsuchy ?

**Comment by mkutlak** [comment]
Version of postgresql?

**Comment by marusak** [comment]
> Version of postgresql?

No, of the postgresql-semver image we are gonna release.  It may happen in the future, that we make some changes, that won't be compatible with older version and if someone will find this article, so he/she knows, that with which version if works.

**Comment by mkutlak** [comment]
Oh sorry, I meant tag the image by the version of postgresql.

**Comment by marusak** [comment]
I don't think that is a good idea. We may need to release a new image with the same postgresql image version. Maybe `postgresql-version`.0 or something similiar would be possible

**Comment by mkutlak** [comment]
@marusak I've added the versions to the article and changed the date.

**Pull request merged**
